{% set name = "tokenizers" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/huggingface/tokenizers.git
  git_rev: python-v{{ version }}
  patches:
    - 0301-update-lexical-core-because-0.7.4-doesnot-compile.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host:
    - pip {{ pip }}
    - python {{ python }}
    - rust-nightly {{ rust_nightly }}
    - setuptools-rust {{ setuptools_rust }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python {{ python }}

test:
  imports:
    - tokenizers
    - tokenizers.models
    - tokenizers.decoders
    - tokenizers.normalizers
    - tokenizers.pre_tokenizers
    - tokenizers.processors
    - tokenizers.trainers
    - tokenizers.implementations
  commands:
    - python -c "from tokenizers import BertWordPieceTokenizer"
    - python -c "from tokenizers import ByteLevelBPETokenizer"
    - python -c "from tokenizers import CharBPETokenizer"
    - python -c "from tokenizers import SentencePieceBPETokenizer"

about:
  home: https://github.com/huggingface/tokenizers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Fast State-of-the-Art Tokenizers optimized for Research and Production
  description: Fast State-of-the-Art Tokenizers optimized for Research and Production
  doc_url: https://huggingface.co/tokenizers/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
